### ISSUE TITLE
Extend <T> command to operate turnouts on GPIO

### ISSUE THREAD

**Issue by matt-hu** [DCC-EX/CommandStation-EX#48]
It would be useful if it was possibly to set up a turnout that was controlled by the IO pins of the Arduino via something like a relay.

**Comment by FrightRisk** [comment]
We already do that, unless I misunderstand you. https://github.com/DCC-EX/CommandStation-EX/wiki/DCC-EX-Command-Reference#arduino-output-pins

**Comment by matt-hu** [comment]
@FrightRisk I understood that you could use IO pins for sensors, but I hadn't seen the section on outputs. 

This got me thinking, would there be a way to map IO pins to 'virtual' accessory decoders so that software that sends the `<T>` command can still activate turnouts connected to the IO pins?

**Comment by davidcutting42** [comment]
@matt-hu I believe you can probably do this by writing a custom command filter. @Asbelos might have some more info.

**Comment by Asbelos** [comment]
The issue here is the drag of backward compatibility. DCC++ was originally designed to be run from JMRI and the implementation of turnouts was awkwardly split between DCC turnouts which the command station knows about  and other outputs or accessory packets sent by JMRI  which the command station cant tell the difference between a turnout or a cow on the line!So if you are using JMRI there is a way already... otherwise you will have to wait for the next version where we need a major overhaul of this mess. On 1 Nov 2020 08:31, Matt <notifications@github.com> wrote:
It would be useful if it was possibly to set up a turnout that was controlled by the IO pins of the Arduino via something like a relay.

**Comment by matt-hu** [comment]
@Asbelos thank for the help.
